temp_dir = "/media/prataprc/hdd1.4tb/tmp"
dump_url = "http://static.crates.io/db-dump.tar.gz"
git_index_dir = "index"
git_analytics_dir = "analytics"

[git]
loc_repo = "/media/prataprc/hdd1.4tb/db-rdms-crio"
loc_db = ""
user_name = "prataprc"
user_email = "prataprc@gmail.com"

[git.init]
bare = false
no_reinit = true
permissions = "shared_umask"
description = "repository holds data from crates.io db dump"

[git.open]
no_search = true
