key_type = "u64"
value_type = "u64"
key_size = 16
value_size = 16
spin = false
cas = false
loads = 10_000_000
sets = 1_000_000
ins = 1_000_000
rems = 100_000
dels = 0
gets = 1_000_000
writers = 1
readers = 16
validate = true
